removed tests from github build for faster routines

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -72,41 +72,41 @@ jobs:
           fi
 
   # Job 2: Run unit tests for all of the plugin
-  plugin_unit_tests:
-    name: Run plugin unit tests
-    needs: update-lockfile
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        group: [1, 2]
-    env:
-      PLUGIN_TESTS_CI_NODE_TOTAL: 2
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          ref: ${{ github.head_ref || github.ref_name }}
-          submodules: true
-
-      - name: Install uv
-        uses: astral-sh/setup-uv@v7
-        with:
-          version: ${{ env.UV_VERSION }}
-
-      - uses: actions/setup-python@v6
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
-
-      - name: Run plugin tests
-        env:
-          PLUGIN_TESTS_CI_NODE_INDEX: ${{ matrix.group }}
-        run: |
-          # replace the yaml list with a string, use a `,` to separate the plugins
-          PLUGINS_STRING=$(echo "$PLUGIN_TESTS_PLUGINS_TO_SKIP" | tr '\n' ',' | sed 's/,$//')
-          uv run \
-            --extra plugins \
-            --with "nomad-plugin-tests" \
-            nomad-plugin-tests --plugins-to-skip "$PLUGINS_STRING"
+#  plugin_unit_tests:
+#    name: Run plugin unit tests
+#    needs: update-lockfile
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        group: [1, 2]
+#    env:
+#      PLUGIN_TESTS_CI_NODE_TOTAL: 2
+#    steps:
+#      - uses: actions/checkout@v6
+#        with:
+#          ref: ${{ github.head_ref || github.ref_name }}
+#          submodules: true
+#
+#      - name: Install uv
+#        uses: astral-sh/setup-uv@v7
+#        with:
+#          version: ${{ env.UV_VERSION }}
+#
+#      - uses: actions/setup-python@v6
+#        with:
+#          python-version: ${{ env.PYTHON_VERSION }}
+#
+#      - name: Run plugin tests
+#        env:
+#          PLUGIN_TESTS_CI_NODE_INDEX: ${{ matrix.group }}
+#        run: |
+#          # replace the yaml list with a string, use a `,` to separate the plugins
+#          PLUGINS_STRING=$(echo "$PLUGIN_TESTS_PLUGINS_TO_SKIP" | tr '\n' ',' | sed 's/,$//')
+#          uv run \
+#            --extra plugins \
+#            --with "nomad-plugin-tests" \
+#            nomad-plugin-tests --plugins-to-skip "$PLUGINS_STRING"
 
   # Job 3: Build and Push Docker Image
   build:
@@ -183,52 +183,52 @@ jobs:
       jupyter_image: ${{ env.jupyter_IMAGE }}
 
   # Job 4: Run example upload tests and entrypoint tests
-  run_tests:
-    name: Run example upload tests and entrypoint tests
-    needs: build
-    runs-on: ubuntu-latest
-    env:
-      APP_IMAGE: ${{ needs.build.outputs.app_image }}
-      JUPYTER_IMAGE: ${{ needs.build.outputs.jupyter_image }}
-
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          ref: ${{ github.head_ref || github.ref_name }}
-          submodules: true
-
-      - uses: docker/login-action@v4
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Start containers and check app/jupyter container health
-        working-directory: tests
-        run: |
-          if ! docker compose up -d --quiet-pull --wait; then
-            echo "Containers failed health check."
-            echo "Logs for app:"
-            docker logs app
-            echo "Logs for jupyter:"
-            docker logs jupyter
-            exit 1
-          fi
-
-      - name: Install uv
-        uses: astral-sh/setup-uv@v7
-        with:
-          version: ${{ env.UV_VERSION }}
-
-      - uses: actions/setup-python@v6
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
-
-      - name: Install dependencies
-        run: uv sync --all-extras
-
-      - name: Run tests
-        working-directory: tests
-        run: |
-          export PLUGINS_STRING=$(echo "$PLUGIN_TESTS_PLUGINS_TO_SKIP" | tr '\n' ',' | sed 's/,$//')
-          uv run --extra plugins pytest -p no:warnings -sv
+#  run_tests:
+#    name: Run example upload tests and entrypoint tests
+#    needs: build
+#    runs-on: ubuntu-latest
+#    env:
+#      APP_IMAGE: ${{ needs.build.outputs.app_image }}
+#      JUPYTER_IMAGE: ${{ needs.build.outputs.jupyter_image }}
+#
+#    steps:
+#      - uses: actions/checkout@v6
+#        with:
+#          ref: ${{ github.head_ref || github.ref_name }}
+#          submodules: true
+#
+#      - uses: docker/login-action@v4
+#        with:
+#          registry: ${{ env.REGISTRY }}
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Start containers and check app/jupyter container health
+#        working-directory: tests
+#        run: |
+#          if ! docker compose up -d --quiet-pull --wait; then
+#            echo "Containers failed health check."
+#            echo "Logs for app:"
+#            docker logs app
+#            echo "Logs for jupyter:"
+#            docker logs jupyter
+#            exit 1
+#          fi
+#
+#      - name: Install uv
+#        uses: astral-sh/setup-uv@v7
+#        with:
+#          version: ${{ env.UV_VERSION }}
+#
+#      - uses: actions/setup-python@v6
+#        with:
+#          python-version: ${{ env.PYTHON_VERSION }}
+#
+#      - name: Install dependencies
+#        run: uv sync --all-extras
+#
+#      - name: Run tests
+#        working-directory: tests
+#        run: |
+#          export PLUGINS_STRING=$(echo "$PLUGIN_TESTS_PLUGINS_TO_SKIP" | tr '\n' ',' | sed 's/,$//')
+#          uv run --extra plugins pytest -p no:warnings -sv
